// Code generated by go-swagger; DO NOT EDIT.

// Package handler Enrichment Service API
//
//	API to enrich and manage information about individuals
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /api
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package handler
