// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeletePeopleIDNoContentCode is the HTTP code returned for type DeletePeopleIDNoContent
const DeletePeopleIDNoContentCode int = 204

/*
DeletePeopleIDNoContent Person deleted successfully

swagger:response deletePeopleIdNoContent
*/
type DeletePeopleIDNoContent struct {
}

// NewDeletePeopleIDNoContent creates DeletePeopleIDNoContent with default headers values
func NewDeletePeopleIDNoContent() *DeletePeopleIDNoContent {

	return &DeletePeopleIDNoContent{}
}

// WriteResponse to the client
func (o *DeletePeopleIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}
