// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetPeopleHandlerFunc turns a function with the right signature into a get people handler
type GetPeopleHandlerFunc func(GetPeopleParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPeopleHandlerFunc) Handle(params GetPeopleParams) middleware.Responder {
	return fn(params)
}

// GetPeopleHandler interface for that can handle valid get people params
type GetPeopleHandler interface {
	Handle(GetPeopleParams) middleware.Responder
}

// NewGetPeople creates a new http.Handler for the get people operation
func NewGetPeople(ctx *middleware.Context, handler GetPeopleHandler) *GetPeople {
	return &GetPeople{Context: ctx, Handler: handler}
}

/*
GetPeople swagger:route GET /people getPeople

Get people with filters and pagination
*/
type GetPeople struct {
	Context *middleware.Context
	Handler GetPeopleHandler
}

func (o *GetPeople) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetPeopleParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
