// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Kartochnik010/test-effectivemobile-jan/internal/models"
)

// GetPeopleIDOKCode is the HTTP code returned for type GetPeopleIDOK
const GetPeopleIDOKCode int = 200

/*
GetPeopleIDOK Person information

swagger:response getPeopleIdOK
*/
type GetPeopleIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Person `json:"body,omitempty"`
}

// NewGetPeopleIDOK creates GetPeopleIDOK with default headers values
func NewGetPeopleIDOK() *GetPeopleIDOK {

	return &GetPeopleIDOK{}
}

// WithPayload adds the payload to the get people Id o k response
func (o *GetPeopleIDOK) WithPayload(payload *models.Person) *GetPeopleIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get people Id o k response
func (o *GetPeopleIDOK) SetPayload(payload *models.Person) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPeopleIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
