// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Kartochnik010/test-effectivemobile-jan/internal/models"
)

// GetPeopleOKCode is the HTTP code returned for type GetPeopleOK
const GetPeopleOKCode int = 200

/*
GetPeopleOK List of people

swagger:response getPeopleOK
*/
type GetPeopleOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Person `json:"body,omitempty"`
}

// NewGetPeopleOK creates GetPeopleOK with default headers values
func NewGetPeopleOK() *GetPeopleOK {

	return &GetPeopleOK{}
}

// WithPayload adds the payload to the get people o k response
func (o *GetPeopleOK) WithPayload(payload []*models.Person) *GetPeopleOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get people o k response
func (o *GetPeopleOK) SetPayload(payload []*models.Person) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPeopleOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Person, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
