// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Kartochnik010/test-effectivemobile-jan/internal/models"
)

// PostPeopleCreatedCode is the HTTP code returned for type PostPeopleCreated
const PostPeopleCreatedCode int = 201

/*
PostPeopleCreated Person added successfully

swagger:response postPeopleCreated
*/
type PostPeopleCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Person `json:"body,omitempty"`
}

// NewPostPeopleCreated creates PostPeopleCreated with default headers values
func NewPostPeopleCreated() *PostPeopleCreated {

	return &PostPeopleCreated{}
}

// WithPayload adds the payload to the post people created response
func (o *PostPeopleCreated) WithPayload(payload *models.Person) *PostPeopleCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post people created response
func (o *PostPeopleCreated) SetPayload(payload *models.Person) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostPeopleCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
