// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutPeopleIDHandlerFunc turns a function with the right signature into a put people ID handler
type PutPeopleIDHandlerFunc func(PutPeopleIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutPeopleIDHandlerFunc) Handle(params PutPeopleIDParams) middleware.Responder {
	return fn(params)
}

// PutPeopleIDHandler interface for that can handle valid put people ID params
type PutPeopleIDHandler interface {
	Handle(PutPeopleIDParams) middleware.Responder
}

// NewPutPeopleID creates a new http.Handler for the put people ID operation
func NewPutPeopleID(ctx *middleware.Context, handler PutPeopleIDHandler) *PutPeopleID {
	return &PutPeopleID{Context: ctx, Handler: handler}
}

/*
PutPeopleID swagger:route PUT /people/{id} putPeopleId

Update person by ID
*/
type PutPeopleID struct {
	Context *middleware.Context
	Handler PutPeopleIDHandler
}

func (o *PutPeopleID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutPeopleIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
